### ISSUE TITLE
release on npm

### ISSUE THREAD

**Issue by smeijer** [marteinn/The-Big-Username-Blacklist#10]
Would be awesome if this project was also released on [npm](npmjs.com). Currently, there is [Mottie/github-reserved-names](https://github.com/Mottie/github-reserved-names), but this project has a lot more reserved names.

```js
const blacklist = require('the-big-username-blacklist');

if (blacklist.indexOf(username) > -1) {
  throw Error(`username '${username}' is reserved`);
}
```

**Comment by marteinn** [comment]
Hi @smeijer! This project actually exists on npm (https://github.com/marteinn/The-Big-Username-Blacklist-JS).

**Comment by smeijer** [comment]
Unfortunately, that version is running behind. This package had received some updates this year, the `JS` version has not. For example, `.htaccess`, `.htpasswd` and `.well-known` are not included in the `JS` version.

I think for maintainance it would be more easy to throw the package.json in this repo.

```
// The-Big-Username-Blacklist-JS:
This file was generated by The-Big-Username-Blacklist VERSION=v1.5.0 (at 2017-04-16 14:41:41.816109)
```
