### ISSUE TITLE
Probable typo in line 137

### ISSUE THREAD

**Issue by rbstrachan** [marteinn/The-Big-Username-Blacklist#13]
I don't want to assume anything, but should line 137 be `ecdh-sha2-nistp512` instead of `ecdh-sha2-nistp521`?

**Reference**
[[1] - The Big Username Blacklist, list_raw.txt (line 137)](https://github.com/marteinn/The-Big-Username-Blacklist/blob/master/list_raw.txt#L137)

**Comment by marteinn** [comment]
Hi @rbstrachan! You are correct - fixed in https://github.com/marteinn/The-Big-Username-Blacklist/commit/e2091beb3f236668b78484323ec2beb493f6169d
