### ISSUE TITLE
Usernames that should be blocked for non-technical reasons

### ISSUE THREAD

**Issue by raphaelschaad** [marteinn/The-Big-Username-Blacklist#19]
It seems this list is focused on blocking **technical** terms that are potentially harmful. What's a good practice to block usernames that are otherwise illegal or inappropriate?

If the scope of this list wants to stay focused on technical terms, a pointer in the README could be beneficial. Happy to help contribute.

**Comment by SuperSandro2000** [comment]
From the readme:

> Please note that this list does not contain any curse words, there are other lists for that.

**Comment by raphaelschaad** [comment]
What lists could you point me (and hopefully others) to there?

Also, I'd be even more interested in best practices not just for profanity but actually legally problematic words (e.g. racist terms).

**Comment by SuperSandro2000** [comment]
There is a link in the readme to https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words.

> Also, I'd be even more interested in best practices not just for profanity but actually legally problematic words (e.g. racist terms).

That is very dependent on culture and geographic region and world wide not possible.

**Comment by marteinn** [comment]
I'm closing this issue as I see the answer posted as resolved. Thanks @SuperSandro2000 for providing support!
